FROM python:3.12-slim

# Node.js setup
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_PATH=/app/node_modules

# node.js deps
COPY package*.json ./
RUN npm install


# copy project
COPY . .

# Exposed port
EXPOSE 3003

CMD ["node", "server.js"]
